#!/usr/bin/expect -f

set DEVICE [lindex $argv 0]

# effectue le transfert par SFTP (sur SSH)

set timeout 3600

spawn sftp gothdroid@gothdroid.com
expect "*sword*"
send -- "AmyLee$33450\n"
expect "sftp>"
send -- "cd /data/opendelta/last/$DEVICE\n"
send "lcd /data/opendelta/last/$DEVICE\n"
send -- "rm /data/opendelta/last/$DEVICE/*.zip\n"
send -- "ls\n"
send -- "put *.zip\n"
send -- "ls\n"
send -- "bye\n"

exit 0
